import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans?.variable} ${geistMono?.variable} antialiased`}
      >
        {children}
        {/* Version Info - visible on all pages */}
        <div className="fixed bottom-2 left-1/2 -translate-x-1/2 text-xs text-gray-400 z-50 select-none pointer-events-none">
          version: 2.0
        </div>
      </body>
    </html>
  );
}
